version: '2'
services:
  meteor:
    build:
      context: .
      dockerfile: Dockerfile.development
    ports:
      - "3000:3000"
    volumes:
      - ${PWD}:/app
    links:
      - mongo
    environment:
      -  MONGO_URL=mongodb://mongo:27017/meteor
  test:
    command: ./start_test.sh
    build:
      context: .
      dockerfile: Dockerfile.development
    ports:
      - "3000:3000"
    volumes:
      - ${PWD}:/app
    links:
      - mongo
    environment:
      -  MONGO_URL=mongodb://mongo:27017/meteor    
  mongo:
    image: mongo:3.0.14 
